# Generated by Django 5.1.7 on 2026-03-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_notification_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_preferences',
        ),
    ]
