# Generated by Django 5.1.7 on 2026-03-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_agreed_to_terms_user_terms_agreed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='agreed_to_terms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='terms_agreed_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token_created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
