# Generated by Django 5.1.7 on 2026-03-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ipattempt_emailverification_last_request_at_and_more'),
        ('accounts', '0006_alter_user_options_user_agreed_to_terms_and_more'),
    ]

    operations = [
    ]
